[package]
name = "ipfs-effector-imports"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipfs-effector-types = { workspace = true }
marine-rs-sdk = { workspace = true }
