#modules_dir = "../../target/wasm32-wasi/release/"
modules_dir = "."
total_memory_limit = "Infinity"

[[module]]
    name = "curl_effector"
    logger_enabled = true
    [module.mounted_binaries]
    curl = "/usr/bin/curl"
    [module.wasi.mapped_dirs]
    "/tmp/vault" = "test_artifacts/temp"
